InverseProbWeights <- function(propensity_scores,num_ctr,num_trt,county_lvl_pop,outcomes) {
  ##############################################################################
  # Calculates the Inverse Probability weights for a population partitioned into
  # county level treatment populations.
  #
  # Input:
  #   propensity_scores - Propensity scores generated by some process (matching)
  #   num_ctr - Control population number
  #   num_trt - Treatment population number
  #   county_lvl_pop - Population partitioned into county level treatment and 
  #                    control numbers.
  #   outcomes - outcomes for the population with key for control and treatment
  #
  ##############################################################################
  assign_key <- county_lvl_pop$Assignment
  county_pop <- county_lvl_pop$County_Total
  num_counties <- county_lvl_pop$Num_Counties  
  tot_pop <- county_lvl_pop$Total
  
# Some extra formatting incase we need it later
# county_trt <- county_lvl_pop %>%
#  filter(Assignment == 1) %>%
#    group_by(County) %>%
#   summarise(County_Trt_N = n(), .groups = "drop")
#  
#  county_ctr <- county_lvl_pop %>%
#    filter(Assignment == 0) %>%
#    group_by(County) %>%
#    summarise(County_Ctr_N = n(), .groups = "drop")
  
  county_counts <- full_join(county_trt, county_ctr, by = "County") %>%
    replace_na(list(County_Trt_N = 0, County_Ctr_N = 0))
  
  lhs_sum <- sum((county_pop / tot_pop)*(assign_key / propensity_scores) * outcomes)
  rhs_sum <-sum( (county_pop / tot_pop)* (1 - assign_key) / (1 - propensity_scores)* outcomes)
 
  estimator <- lhs_sum - rhs_sum
  return(estimator)
}